### ISSUE TITLE
Creating config file does not work

### ISSUE THREAD

**Issue by Isakdl** [gocal/gsheet_to_arb#5]
When running the command

`pub run gsheet_to_arb:import --create-config gsheet_to_arb.yaml`

I get the following error:

```
Unhandled exception:
FormatException: Could not find an option named "create-config".
#0      Parser.validate (package:args/src/parser.dart:261:21)
#1      Parser.parseLongOption (package:args/src/parser.dart:250:7)
#2      Parser.parse (package:args/src/parser.dart:90:11)
#3      ArgParser.parse (package:args/src/arg_parser.dart:320:45)
#4      main (file:///Users/isak/.pub-cache/hosted/pub.dartlang.org/gsheet_to_arb-0.0.6/bin/import.dart:24:10)
<asynchronous suspension>
#5      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
pub failed (255)
```

Could solve the issue by creating the config manually from the template file.

**Comment by gocal** [comment]
now the config can be created with 
```
pub run gsheet_to_arb:import --create-config 
```
